### ISSUE TITLE
bug in calendula add medicine option

### ISSUE THREAD

**Issue by djavalord** [citiususc/calendula#100]
#### Expected behavior
I expect that once I click on medicine, then click on the + sign to add medicine, I should be able to type a medicine name and add to Med kit, then a new page that will enable me enter other Info/data of the medicine.

#### Actual behavior
When I Clicked on the medicine then the + sign to add medicine, after typing the medicine, I clicked add to the Med kit, the app returned me to the point where I typed the medicine. When I clicked on the return key to return to the previous page, I did not return

#### How to reproduce
Download Calendula Version 2.5.3(34) from Google play store. Install then launch, click on the menu key by the top left hand side, select medicines, click on the + sign to add medicine, then type the medicine name (say xyz) click on add ‘xyz ‘to Med kit, then click on the return key by the top left hand side of the app.

* Browser: Calendula Version 2.5.3(34)
* Operating system: Android 5.1.1 Lollipop. Infinix hot 3 LTE

#### Recording Of The Bug
https://youtu.be/WMHQAcdaUTE
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@javalord/bug-in-calendula-add-medicine-option">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by ontherunvaro** [comment]
This bug has been fixed in [release v2.5.4](https://github.com/citiususc/calendula/releases/tag/v2.5.4). Please let us know if it persists. Thank you!
