### ISSUE TITLE
Take vs Taken

### ISSUE THREAD

**Issue by coconutoil** [citiususc/calendula#101]
Hi, I like the app in general, but the phrasing of "Take" on the notification confuses me. 
It's a small thing but nonetheless it irks me every time I see it.
It seems like you hit that button only _after_ you've taken the med so it should be "Taken"
Is this something that's been discussed before?

**Comment by ontherunvaro** [comment]
This has been done in [release 2.5.4](https://github.com/citiususc/calendula/releases/tag/v2.5.4). It now shows 'Taken'. Cheers!
