### ISSUE TITLE
bug found in calendula when try to check for update

### ISSUE THREAD

**Issue by muhammadarif1** [citiususc/calendula#106]
#### Expected behavior
this application should allow users to check for updates if available with check update feature that has been provided
#### Actual behavior
but when i try to use that feature this app get crashed and stoping itself

#### How to reproduce
- download the app
- launc the app
- select the option in the third line on the left sides
- go to setting
- chose option medicine database 
- and click "check for upddate "option and note the bug

* Browser: calendula v 2.5.3
* Operating system: android lolipop 5.1 idos

#### Recording Of The Bug
https://youtu.be/2lLd67gxvDM

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@muhammadarif/bug-found-in-calendula-when-try-to-check-for-update">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by ontherunvaro** [comment]
Hi @muhammadarif1,

Unfortunately, we can't reproduce this behaviour. Would you be able to provide us with a logcat?

**Comment by ontherunvaro** [comment]
Closed because of no response
