### ISSUE TITLE
All medicine barcodes scanned say medicine does not exist.

### ISSUE THREAD

**Issue by Claude12** [citiususc/calendula#111]
@ontherunvaro all the medicine barcodes i try to scan to add the medicine say medicine does not exist even those that appear when i search using their name.Can you help me by sending pictures of working medicine barcodes that will be picked if i search using a barcode for testing purposes.

can you email them to me at csachinda@gmail.com

Thank you.

**Comment by ontherunvaro** [comment]
Hi, medicine barcodes are checked against the installed med DB. At present time, only the Spanish AEMPS DB is available.
Any med sold in Spain should do. If you're trying to scan meds from other countries, you need a database first!
