### ISSUE TITLE
When enabling AEMPS database, warn user that it's country-specific to Spain

### ISSUE THREAD

**Issue by scruloose** [citiususc/calendula#114]
When I installed Calendula, I had never heard of AEMPS, so I assumed it was some sort of international open-med-database, like an OpenStreetMaps project for medications. Presumably most users who don't live in Spain a) won't have heard of AEMPS and b) will find it utterly useless, especially if they are not in a Spanish-speaking locale.

Solution: On initial setup, if the user enables the AEMPS Database, pop up a dialog to specifically warn the user that it's a Spanish-language database and all the information it contains is specific to Spain's pharmacy system.

**Comment by ontherunvaro** [comment]
Hi @scruloose ,

Thanks for bringing this up! Since we are Spanish, somethings these kinds of things slip by. Nonetheless, I think another popup would be a bit cumbersome, so what I think we'll do is add the country name next to the DB name, like "AEMPS (Spain)" to avoid confusion.

**Comment by scruloose** [comment]
Heh! Fair enough. It's easy to take one's own context for granted, and not so easy to anticipate what details other people are not aware of.

Just adding the country name would solve the problem. If you want to go a little further, I think Android allows items in a list to have additional descriptive text that becomes visible only when the item is selected, so you could have *"Locale: Spain -- Language: Spanish"* or *"Spain only!"* or similar show up dynamically, while keeping the main list view clean and avoiding a cumbersome popup. I'm no Android programmer, and I have no idea what that functionality is called.

**Comment by hanndecl** [comment]
In Belgium we have a similar database. What is the procedure to add such a database in Calendula?

**Comment by ontherunvaro** [comment]
@hanndecl There's no standard procedure. Currently  DBs require an adapter (see [AEMPSPrescriptionDBMgr.java](https://github.com/citiususc/calendula/blob/master/Calendula/src/main/java/es/usc/citius/servando/calendula/drugdb/AEMPSPrescriptionDBMgr.java) for example).

We've thought of using some kind of "standard", format but we always lose some useful information if we do that compared with custom adapters, so we've not taken the step. So for now the only way to add a new database would be PRing a functioning DBMgr with the corresponding DB file.
