### ISSUE TITLE
Calendula app gets crashed.

### ISSUE THREAD

**Issue by Sammaz2** [citiususc/calendula#117]
### Actual behavior
When I opened the calendula opensource android app. And after that I clicked on the options present on the top left corner of the page. And then I clicked on settings option. After that I clicked on medicine database. And then I selected a database. After that I clicked on check for updates. Then I pressed back button twice. Suddenly the app crashed.

### How to reproduce

* First you need to download the app from fdroid and then install it, after that open the app.

* Click on the options present on the top left corner of the page.

* And then click on settings option.

* After that click on medicine database.

* Then select a database and click on check for updates. After that press get back to mainscreen of the app. Suddenly the app will get crashed.

https://youtu.be/eZrmNr00tCY 

* Browser: Calendula

* Version: 2.5.5

* Operating system:7.1.2

* Device model: Redmi 4

**Comment by ontherunvaro** [comment]
Hi, we can't reproduce this, and we can't really know what is happening.

If you can send us a logcat, we may be able to use it for debugging.

**Comment by ontherunvaro** [comment]
Cloased for lack of response.
