### ISSUE TITLE
Calendula app crashes when accessing notification settings

### ISSUE THREAD

**Issue by jubreal** [citiususc/calendula#118]
#### Expected behavior
The app should remain stable and should not crash when notifications sound is changed. 

#### Actual behavior

The app crashes when a new notification sound is selected and continues subsequent crashes that ensures users can no  longer  notification settings.

#### How to reproduce

Download and install latest app version

Click on settings (This can be accessed by clicking on the 3 lines in the top left corner of the app)
 
Rotate phone to landscape mode

Click on notifications 

Change notification sound  to an mp3 song preferably

The app crashes and notification sound  cannot be accessed again until it is re-installed

* Browser/App version: Calendula app version 2.5.5
*Operating system: Android 6.0

#### Recording Of The Bug
This is the recording showing the crash when trying to set the notifications settings
https://youtu.be/Mq7dT0daAIA

This is the recording showing subsequent crashes
https://youtu.be/RPYrDiEuX4U

**Comment by ontherunvaro** [comment]
Hi.

While we can't reproduce this, I may have an idea where this is coming from. If you check your app permissions, does Calendula have the storage permission enabled?

**Comment by jubreal** [comment]
Yes you are right.  It was due to permission issues.
Thanks

**Comment by ontherunvaro** [comment]
Alright, we've had similar issues in the past with Android distributions that request permission when it theoretically isn't needed.

Are you using MIUI by any chance?

**Comment by jubreal** [comment]
No I'm not

**Comment by ontherunvaro** [comment]
Hi, does this error persist in the latest version (2.5.8)

**Comment by ontherunvaro** [comment]
Closing for lack of response
