### ISSUE TITLE
context.startService(serviceIntent); is causing daily crashes at 1 am

### ISSUE THREAD

**Issue by suhaibibrahim** [citiususc/calendula#127]
Hello,

I have noticed that the following code : context.startService(serviceIntent); in  calendula/Calendula/src/main/java/es/usc/citius/servando/calendula/scheduling/AlarmReceiver.java is causing daily crashes when the app tries to create the daily schedules for the pills.

This is the error message:
java.lang.IllegalStateException: Not allowed to start service Intent

The root cause of this issue is caused by the api 26 and above, here are some details:

https://stackoverflow.com/questions/46445265/android-8-0-java-lang-illegalstateexception-not-allowed-to-start-service-inten

JobScheduler should be used instead.

Regards

**Comment by ontherunvaro** [comment]
This shouldn't happen since [our target API is 25](https://github.com/citiususc/calendula/blob/master/Calendula/build.gradle#L79). 

Can you share your phone details? i.e:

* Phone make and model
* Android system version number
* Type of Android ROM (manufacturer/custom/MIUI/etc.)

**Comment by suhaibibrahim** [comment]
you are correct, I increased the target api to avoid this error warning:

Target API level requirements from August 2018
Warning:

Your app currently targets API level 25 and must target at least API level 26 to ensure it is built on the latest APIs optimized for security and performance.

From August 2018, new apps must target at least Android 8.0 (API level 26).
From November 2018, app updates must target Android 8.0 (API level 26).

Tip:

Change your app's target API level. Learn how.

are you planning to target the latest API? YOu might need to consider the issue above and another few changes in remindernotification.java since you need to add a channel ID to it on the latest API.

**Comment by ontherunvaro** [comment]
Yes, we're definitely going to update the target API at some point, since we wouldn't be able to push updates otherwise. However we've got no ETA for this yet. 

Of course, if you or anyone else wants to contribute, PRs are always welcome!

**Comment by ontherunvaro** [comment]
@suhaibibrahim I've already made  the needed changes [in the `develop` branch](https://github.com/citiususc/calendula/commit/feb6d434c3b13d01c9875cfb4fffb7d1718993be).

I will close this issue as soon as it's merged into `master`. Thanks for reporting!

**Comment by suhaibibrahim** [comment]
Fantastic work ! Thank you.

**Comment by ontherunvaro** [comment]
Merged into release 2.5.7. Cheers!
