### ISSUE TITLE
Request for copywriting on FAQ

### ISSUE THREAD

**Issue by ayibam** [citiususc/calendula#128]
Hi,
I have signed the agreement and would want to contribute via creating a FAQ for the project.

**Comment by ontherunvaro** [comment]
Hello, 

If you want to contribute a FAQ you may do so via pull request. Thanks for the interest!

**Comment by ayibam** [comment]
Thank you, would get on it

**Comment by ayibam** [comment]
Hi, I have made a document for FAQ for your review. Please check and correct,so I make adjustments. I would make it in mark down format once you vet it, and make a pull for it

What is Calendula?
Calendula is an app developed by the *Singular Research Center in Information Technology of the University of Santiago de Compostela (CiTIUS)* help users improve the level of adherence to medication with and easy to use interface at no cost. Thus the importance of taking medication at the appropriate time and developed this project to help users get better quickly and also find time to think about other necessary things.
What data does Calendula collects?
Calendula doesn’t collect any personal information.
Calendula has access to my mobile data?
Calendula only access the internet via you device to download medicine prospects to offer consultation services. This is however only limited to the online information center of the Spanish Agency for Medicines and Health Products, which is required when adding your list of medicine.
How do I check my daily schedule on Calendula?
Click the *icon at the top right corner of the home screen*; this would display a 24 hour schedule for your medications.
Can I add more than one patient schedule on my Calendula?
Yes, by simply clicking on the *menu button at the top left side of your screen*, select the icon *Patients* click the **+ button** at the button of the page, and type in the patients name and save by clicking the *done* button at the top right corner of the page.
How do I add my prescription schedule?
Click on the *menu icon at the top left corner of the home screen*, select *schedules* and click on **+**, this would give you three options to choose *Routine schedule, Dosing interval and Period + rest*. Choose which ever is applicable to you. 
On selecting your preferred option, click **+** to select the medicine needed for this schedule, once done with that. Click schedule to specify the exact time or period of the day and number of dose required, once done here you can now go to summary to check and confirm your selection.
How do I secure my data on my device?
Click the *menu button at the top left corner of the page*, select *settings* click *privacy* click on *app lock* to set your preferred **pin**, there is also an option for fingerprint lock if your device is fingerprint enabled.
You can also opt for automatic lock timer on the app.
Can I add my preferred ringtone to Calendula?

**Comment by ontherunvaro** [comment]
As I've stated in the accompanying pull request, while we understand and are grateful for your interest to contribute, we feel like the writing on this needs a lot of polishing. I'm closing this issue for now.
