### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by XXX-21** [citiususc/calendula#137]
![error](https://user-images.githubusercontent.com/15707285/44857018-4fd9be80-ac88-11e8-92ad-f520c0152138.PNG)

**Comment by XXX-21** [comment]
please help me out how to solve it

**Comment by ontherunvaro** [comment]
You're going to need to find a more specific cause, the error says "see log for more details".

Have you changed any file, or is this up to date with our repo?

**Comment by XXX-21** [comment]
no, I didn't change any file.

**Comment by ontherunvaro** [comment]
Alright, so as I said, you will need to find a more specific error.

The "java" group at the left in your screenshot also shows an error icon, maybe there's some more info there.

**Comment by ontherunvaro** [comment]
Closed for lack of activity
