### ISSUE TITLE
Calendar view shows all hours from 00 to 23

### ISSUE THREAD

**Issue by SeZuo** [citiususc/calendula#138]
That's a lot of wasted space and scrolling. May I suggest to collapse empty hours, days, weeks, etc. ?

On a side note, it would be nice to have a summary view in tables, and the option of not taking some meds actively.

**Comment by ontherunvaro** [comment]
There _is_ a summary view that does not show empty hours. Just click the "expand" button on the top right corner of the main page.

**Comment by SeZuo** [comment]
Thanks @ontherunvaro. My take is that summary view shows what's next, and expanded view shows a 3-day time span. I don't see the point of the hour grid, it certainly looks good, but serves little purpose.

(great app by the way)

**Comment by ontherunvaro** [comment]
Well, the hour grid is supposed to give a reference for the intakes so as to gain an intuition of how they are distributed throughout the day.  
Moreover, if one has many schedules and intakes, it can be easier to understand than a collapsed view.

If I understand correctly, you would like to see the same type of view (as in the 3-day span), but with empty hours collapsed?

**Comment by SeZuo** [comment]
Ok, I understand. I use the expanded view to check if I skipped or not the last intakes. With the purpose you've given, the hour-grid makes more sense.
