### ISSUE TITLE
Generate an empty SQLite database during build

### ISSUE THREAD

**Issue by Riduidel** [citiususc/calendula#139]
THis database could be given as input to [SchemaSpy](https://sourceforge.net/projects/schemaspy/files/schemaspy/SchemaSpy%205.0.0/) in order to obtain a good documentation of calendula DB.

Even better, we could also create database similar to the production one, which makes schema dump way more useful.

**Comment by ontherunvaro** [comment]
If I'm not mistaken, you can pull the empty SQLite file from an emulator/Android device using ADB just after installation.  It should be under `/data/data/es.usc.citius.servando.calendula/databases/calendula.db `.

You may need to use `adb root` to be able to access this path, however.

**Comment by Riduidel** [comment]
I find that method rather tedious.

I would better have the build process generate the DB, then create 
documentation diagram from that DB automatically. I'll try that this 
evening.


Le 17/10/2018 à 14:35, Álvaro Brey a écrit :

**Comment by Riduidel** [comment]
So, I've added a test in `DBTest` which full content is 

    /**
     * Abuse test framework to export database into a project folder, allowing further analysis of database schema
     */
    @Test
    fun exportDatabase() {
        val db = DB.helper().writableDatabase;
        val destination = File("../db")
        destination.mkdirs()
        System.out.println(String.format("Exporting application database %s to %s", db.path, destination.absolutePath))
        FileUtils.copyFileToDirectory(File(db.path), destination)
        assertNotNull(db.path);
    }

It works ... correctly, since I indeed have a `db/calendula.db` file generated.
But it seems to be incomplete. As an example, I can't find the `ActiveIngredients` table that should be generated by the `ActiveIngredientDAO` init code. I'm still debugging, but am quite confused.

**Comment by ontherunvaro** [comment]
Hi,

Is this a robolectric test, or just a plain JUnit one? You should make sure `DatabaseHelper.init(Context)` is called sometime before you get the file.

If it is a robolectric test the framework should already call this on application startup, but in case of a JUnit test you may need to call it manually.

**Comment by ontherunvaro** [comment]
By the way, if you use a debug flavor, you can use Chrome to inspect the database via Stetho.
Just open a chrome window in your PC, go to chrome://inspect#devices, and you should find the database under Resources > Web SQL.

**Comment by angelpinheiro** [comment]
Calling `DB.helper().close()` before copying the file does the trick for me! I assume it's probably due to some pending SQLite statement that now is forced to finish.

```
    @Test
    fun exportDatabase() {
        val dbPath = DB.helper().writableDatabase.path
        DB.helper().close()
        val destination = File("../db")
        destination.mkdirs()
        System.out.println(String.format("Exporting application database %s to %s", dbPath, destination.absolutePath))
        FileUtils.copyFileToDirectory(File(dbPath), destination)
        assertNotNull(dbPath)
    }

```

**Comment by ontherunvaro** [comment]
Closing this issue since the relevant PR is merged, and this is related to development, so no need to wait for release.
