### ISSUE TITLE
Use HH format instead of kk to display time

### ISSUE THREAD

**Issue by Sparow199** [citiususc/calendula#144]
| | | 
|:-------------------------:|:-------------------------:|
|<img width="1604" alt="screen shot before" src="https://user-images.githubusercontent.com/22281426/47258056-02165100-d496-11e8-985d-72f48806446e.jpg">|  <img width="1604" alt="screen shot after" src="https://user-images.githubusercontent.com/22281426/47258043-e0b56500-d495-11e8-818e-8d3909fa6bea.jpg">|

**Comment by ontherunvaro** [comment]
Reopening this, please don't close until this is merged to master! Cheers!
