### ISSUE TITLE
High battery usage

### ISSUE THREAD

**Issue by xkill** [citiususc/calendula#150]
Hi,

Yesterday I setted up new medical plan (2 medicine each 8 hours). And calendula started to drain the battery very fast.

I'm subscribed to beta tester on Google Play.

Screenshot: https://cloud.locolandia.net/s/fC3oreKCxXLRzHb

**Comment by ontherunvaro** [comment]
That is strange, since it actually says it's been in use for 0 minutes in background, and only 3 in foreground. What is your phone make/model and Android version?

**Comment by ontherunvaro** [comment]
Closed as stale
