### ISSUE TITLE
Crash: When only using the short notification and not the insistent

### ISSUE THREAD

**Issue by TobiasDev** [citiususc/calendula#158]
I want to use this app with only a short notification and not a repeating alarm but when I only want to use the short the app chrashes instead of reminding me (technically that is a reminder but not what I was expecting. :D)

**Comment by ontherunvaro** [comment]
Hi @TobiasDev, can you check which version of Calendula you are using? If it's 2.5.10, please update to 2.5.11, since the bug you describe was known in 2.5.10.

**Comment by TobiasDev** [comment]
Aha. Yeah, that seems to be the latest on F-Droid,  so I guess I'll wait for the update! Thanks for letting me know. :)

**Comment by ontherunvaro** [comment]
Nice, when you update, if the problem goes away please close this issue. Cheers!

**Comment by TobiasDev** [comment]
Yep! Works in latest. :)
