### ISSUE TITLE
Notifications don't work

### ISSUE THREAD

**Issue by sandy-8925** [citiususc/calendula#161]
I have created schedules, but I never receive notifications for those schedules. I am using a OnePlus 5, with Android 9.0 (but had Android 8.1 until a few days ago).

**Comment by sphh** [comment]
Calendula has to be excluded from battery optimization and power manager as every app running in the background wanting to display notifications.

On my Android 8.1 I had to do the following:

1. Open `Settings`, select `Battery`, click on the three vertical dots in the top right corner and select `Battery optimization`. Check if `Calendula` is in the list of `Not optimized` applications. If it is not, tap on `Not optimized`, select `All apps`. Scroll down to `Calendula` and tap on it. Select `Don't optimize` and `Done`. Go back to `Settings` by pressing the back button repeatedly.
2. Back at `Settings`, select `Smart Assistant`, click on `Power save manager` and in the `White list` scroll down to `Calendula` and make the checkbox beside `Calendula` active.

If the procedure is a bit different on Android 9.0, please add it here.

@omideleayo, maybe you want to add this procedure to your FAQ #133 ?

**Comment by sandy-8925** [comment]
My OnePlus device has some additional power management "features" that break expected Android behaviour.

I suggest disabling them, since it prevented Calendula (and other apps') notifications from working.

**Comment by sandy-8925** [comment]
My bug was due to OnePlus' power management changes that broke expected Android API behavior, so it's not a bug in Calendula.

After disabling OnePlus' power management features, Calendula now works correctly.

Note that I have not disabled Android's default battery optimization features.

I'll close this now.

**Comment by sphh** [comment]
Glad that it works now.
