### ISSUE TITLE
Calendula splash screen appears two shortly when accessing the application upon an alarm

### ISSUE THREAD

**Issue by rrodrigueznt** [citiususc/calendula#32]
When an alarm trigger a user's action, Calendula splash screen displays for less than a second. Users are able to see but not to read the sentence below the logo. I do think this time must be enough for users realize that now error or warning message have been shown!

**Comment by angelpinheiro** [comment]
I think in this situation (when accessing the app from notification) it would be better not to show the welcome screen. It really does not contribute in any way and adds a delay to the action you want to perform.

**Comment by rrodrigueznt** [comment]
I can easily agree on your point! For me both options are acceptable: to show the splahs screen in any case and time enough to be read, or not to show it at all in the circunstances. Thanks!
