### ISSUE TITLE
Why don' t move to the screen where all actions are shown when one of them is marked as done?

### ISSUE THREAD

**Issue by rrodrigueznt** [citiususc/calendula#33]
When an alarm sounds, a user's action is required to mark it as done of delay it. I do think it would be clear of any of those actions closes the action's screen and go back to the general presentation of all medications to be taken during the day. Currently, the user must hit the arrow in the upper-left corner of the screen or the generic Android back bottom.

**Comment by angelpinheiro** [comment]
I think it's a good idea. Probably the best way to do so will be going back to the home screen when an alarm is delayed or when ALL intakes are checked as done.

**Comment by angelpinheiro** [comment]
In the new version of the app available at the `develop` branch there is an "Intake notification Activity" that solves this problem.
