### ISSUE TITLE
App translations (FR/EN)

### ISSUE THREAD

**Issue by rhaamo** [citiususc/calendula#39]
Hi,

In the 1.2.1 (no 1.2.2) in F-DROID there is some non-english labels.
I would love to have this app in French too.
Is there any plans for more traductions ? I would like to help to translate too if you want.

Thanks.

**Comment by angelpinheiro** [comment]
Hi @rhaamo, currently the French translation is not on the road map (mostly for a matter of ignorance) but PR are always welcome. We would appreciate very much your contribution!

I would also be grateful if you could be more specific about those non-English labels. English is the default app language, so if there are non-English labels they are probably hard-coded and therefore they are hard to locate.

Regarding what you mention about F-DROID, I can only say that our only official update path is Google Play, and I'm not aware on how this alternative market or similar work, or which are their update policies. We recommend using Google Play to always have the latest version.

**Comment by rhaamo** [comment]
Hi,
For the untranslated strings, see screenshot : 
![screenshot_2015-04-15-18-46-04](https://cloud.githubusercontent.com/assets/8625/7168296/af49bb56-e3bc-11e4-85e8-deb124be577d.png)
That's the only labels i see untranslated.

About french translation, i see in ```/Calendula/src/main/res/``` a ```values-es/strings-*``` and ```values/strings-*```, i may be able to do a ```values-fr/strings-*``` and submit a PR, is there anything else to translate ? (note that i'm not a java nor android developper :( )

**Comment by angelpinheiro** [comment]
Yep, it is as simple as that. You only need to create a new folder (```values/fr```) and copy the translated resources inside. You just have to be careful with the format arguments (```%1$s!```, ```%2$d```, ...). 
There is nothing more to translate (don't worry about the hard-coded strings, they are already in the resource files, but they are not referenced properly).

**Comment by RunningDroid** [comment]
I found a few more untranslated strings in 2.3.1:
![screenshot_2015-06-10-18-34-13](https://cloud.githubusercontent.com/assets/486393/8096037/efd5e518-0fa0-11e5-87c3-82f044c32a71.png)
![screenshot_2015-06-10-18-35-02](https://cloud.githubusercontent.com/assets/486393/8096042/f9bc5f26-0fa0-11e5-85a4-a023ac692579.png)

**Comment by angelpinheiro** [comment]
Thanks you very much, I'll fix it. Regarding to medicines data, I will probably not be able to change that. I'm using a medicine database from the Spanish Medicines Agency http://www.aemps.gob.es/ (+20000 medicines), and all the names, descriptions, presentations, dosage, etc. are only in Spanish.
