### ISSUE TITLE
Add birth control lady pills schedules

### ISSUE THREAD

**Issue by DJaeger** [citiususc/calendula#40]
It would be great if you could also birth control lady pills and corresponding schedules.
So that you can add cycle times like the following commons:
Days to consume + break
21 + 7
22 + 6
23 + 5
24 + 4
26 + 2
28 + 0
35 + 7
42 + 7
63 + 7
84 + 7

**Comment by angelpinheiro** [comment]
Hi, if you look at branch [https://github.com/citiususc/calendula/tree/support-google-rfc-2445](support-google-rfc-2445), we have recently been working on migrating our internal model to one that supports more flexible schedules. Birth control pill schedules are one of the new features we would like to include in the next version of the app.

**Comment by DJaeger** [comment]
Sounds great

**Comment by DJaeger** [comment]
The new version is out now.
It supports some other schedules, but none of them allows to configure this type of schedule.

**Comment by angelpinheiro** [comment]
If you select the type "period/rest cycle" (last one) you can indicate that kind of schedule:

<img src="https://cloud.githubusercontent.com/assets/5940259/8101782/af4f5888-101a-11e5-9a4d-c410a8acc624.png" width="300px"/>

<img src="https://cloud.githubusercontent.com/assets/5940259/8101783/af506b60-101a-11e5-9042-9c73c73e4cd2.png" width="300px"/>

<img src="https://cloud.githubusercontent.com/assets/5940259/8101784/af93b730-101a-11e5-9a89-735b9576736a.png" width="300px"/>

**Comment by DJaeger** [comment]
Sorry, only searched inside the every day schedule I created until this feature is available.
Have not seen I have to create a different schedule now.
Thanks for implementing this.
