### ISSUE TITLE
rfc2445.jar

### ISSUE THREAD

**Issue by krt16s** [citiususc/calendula#44]
In build.gradle, you use the jar file over the one in central. Is there a reason? Is it just build from the last commit of https://code.google.com/p/google-rfc-2445/source/list ?

````
//compile 'org.scala-saddle:google-rfc-2445:20110304'
compile files('libs/rfc2445.jar')
````

**Comment by angelpinheiro** [comment]
The reason is that the dependency from central adds nearly 3mb to the resulting APK. The jar is built, as you say, from the last commit of google-rfc-2445 repository on google code (r36). I didn't found any alternative repository to avoid including the jar :(

**Comment by krt16s** [comment]
Thanks for pointing out, might be worth to add a short comment in gradle, too.  Build the jar from source and it's working fine. Thanks again.
