### ISSUE TITLE
App crashes once you try to access to "settings"

### ISSUE THREAD

**Issue by mperezCeibal** [citiususc/calendula#46]
The app crashes once you tap on the "settings" item on the menu ("ajustes" since we are using the spanish version) 
the affected version is 2.3.3 running on Android 5.0

**Comment by angelpinheiro** [comment]
Hi, I have received the same issue from users of some specific models such as Motorola Moto E, and I think is related with the alarm tone options on the settings activity. Could you please tell me what is your device model?

**Comment by mperezCeibal** [comment]
Thanks, Ángel for the prompt response. I don't know the exact brand of the the tablet, but it's distribuited by JP http://www.jp-ik.com/ and the model is TC80RA1

Weird thing is that this bug isn't present when running on Android 4.4 (same tablet)

Thanks!

**Comment by angelpinheiro** [comment]
Does the error persist since the last update (v2.3.5)? If so, it would be nice if you could send the report when the app crashes, to look at the error details. Otherwise, it is a bit difficult to correct the issue since I can't reproduce it :(

**Comment by mperezCeibal** [comment]
Ok, I'm gonna try with the newest version, If the error continues I'll try to send you the report. 

Will let you know about the results

**Comment by mperezCeibal** [comment]
Hey Ángel,

Sorry for the delay, The error persists on v2.3.6. We are trying to send you the report with the developement team. On the meantime, I'm attaching a screenshot for you to check
![screenshot_2015-10-09-12-11-39](https://cloud.githubusercontent.com/assets/13852263/10396157/b23c1c98-6e7f-11e5-9f1c-70a1dd314039.png)

**Comment by mperezCeibal** [comment]
Hey Ángel,

The error persists on v2.3.6. We have the report, but unfortunately github is not allowing me to attach it. Please send us contact info for us to send you the report directly
Sorry for the hassle

**Comment by angelpinheiro** [comment]
Hey @mperezCeibal, does the error persist in the latest 2.4 release?

**Comment by ontherunvaro** [comment]
Closing this issue for long-time inactivity and inability to reproduce.
