### ISSUE TITLE
Letters not completely displayed   Contrast could be higher

### ISSUE THREAD

**Issue by paulle** [citiususc/calendula#48]
Letters are not completely displayed (see screenshot)
![screenshot_2015-09-13-09-22-11](https://cloud.githubusercontent.com/assets/4852079/9835744/628716b0-59fa-11e5-8d52-9cab2ccc77aa.png)

Even contrast for some text cold be higher (instead of light grey on white it should be a darker grey, same for light (or pale) blue, this would enhance readability (especially on smaller displays.

**Comment by angelpinheiro** [comment]
I think the new look (on the beta channel) solves this issue. 
<img src="https://dl.dropboxusercontent.com/u/4213618/calendula/multipat/schedules.png" width="250px" />

**Comment by paulle** [comment]
yes, looking much clearer and better. thank you
