### ISSUE TITLE
Alarm time is inexact for API versions => 19

### ISSUE THREAD

**Issue by fabian-z** [citiususc/calendula#52]
> Note: Beginning with API 19 (KITKAT) alarm delivery is inexact: the OS will shift alarms in order to minimize wakeups and battery use. There are new APIs to support applications which need strict delivery guarantees; see setWindow(int, long, long, PendingIntent) and setExact(int, long, PendingIntent). Applications whose targetSdkVersion is earlier than API 19 will continue to see the previous behavior in which all alarms are delivered exactly when requested. 

([Source](https://developer.android.com/reference/android/app/AlarmManager.html))

For my device (running CM13, Android 6.0.1) the alarm times are very unreliable - sometimes more than an hour off. Since this application is supposed to help with medication intake times, I think reliable alarm times should be a critical priority in regards to battery usage - at least as important as your daily wake-up alarm. There are certain medications where even half an hour makes a large difference for the affected patients condition.

Since ```setExact``` only exists on API versions >= 19, conditional branching based on ```Build.VERSION.SDK_INT``` could be needed if support for older API versions must not be dropped.

**Comment by fabian-z** [comment]
I implemented my suggested fix in a testing branch: https://github.com/fabian-z/calendula
Will send a PR when I tested sufficiently.

**Comment by angelpinheiro** [comment]
Fixed on d3028d066ba140e78908074cc485675c917e5e3
