### ISSUE TITLE
Minor typos in spanish

### ISSUE THREAD

**Issue by constantino-garcia** [citiususc/calendula#55]
Opening exclamation marks (¡) are missing in the spanish version of calendula. 

There exist some other minor typos. For example:
 * A period mark is missing in the first screen of the tutorial.
 * In the third screen of the tutorial (Botiquín), "Mantén" should be used.

**Comment by angelpinheiro** [comment]
Closing this since it has been fixed on https://github.com/citiususc/calendula/pull/56
Thanks for the contribution!
