### ISSUE TITLE
Stock of Medicines ( Features )

### ISSUE THREAD

**Issue by bennyadr** [citiususc/calendula#59]
Would You Please add this Feature to Calendula...." Stock or Amount of Medicines Available " when User try to add the new med...then she/he needs to add stock of meds....also capabilities to reduce the amount of stock after user take their meds....i Believe with this feature calendula will be the most excelent meds reminder ever exist....keep the good jobs...thanks alot

**Comment by angelpinheiro** [comment]
Hi @bennyadr! Stock management is one of the features we would like to include in Calendula, and we are thinking on a way to make it transparent for users who are not interested in that feature. Hopefully it will be available soon!

**Comment by ontherunvaro** [comment]
This functionality is now available in release 2.5.1, which is available in the usual places.  Find the stock option in the medicine edit screen (when adding a new med or editing an existent one).

Thanks for the feedback!
