### ISSUE TITLE
Notification does not go away when intakes are confirmed in the application

### ISSUE THREAD

**Issue by CrisBarreiro** [citiususc/calendula#61]
If there is an intake notification, and the intakes are confirmed without accessing the confirmation screen through the notification the notification does not go away. This can happen if the notification appears while the app is open, or if the app is opened from the launcher instead of the notification.

**Comment by rrodrigueznt** [comment]
Same behavior here. I'm running Calendula 2.4 (29) on a Sony Xperia M4 Aqua with Android 5.0.

**Comment by CrisBarreiro** [comment]
I am also running Calendula 2.4, on a Xiaomi Mi4S with Android 7.1.1

**Comment by angelpinheiro** [comment]
Issue fixed in 770a3c207114d7d8e2c3cffaeb17a6efcb63dacd.  It will be on Google Play as soon as possible :grimacing:
