### ISSUE TITLE
F-droid version

### ISSUE THREAD

**Issue by trmendes** [citiususc/calendula#70]
Hi. I guess the version we have at F-droid repository is an old one. Need an update there.

**Comment by ontherunvaro** [comment]
Hi, @trmendes.

Unfortunately, we don't maintain the version of Calendula at FDroid. 
We've looked at why it isn't updated and found some errors that we've already fixed. Now it's up to an FDroid mantainer to update it. You can try opening an issue at the [relevant FDroid repo](https://gitlab.com/fdroid/rfp/issues). 

Thank you!
