### ISSUE TITLE
"Final intake" field for hourly interval schedules

### ISSUE THREAD

**Issue by symbolisch1234** [citiususc/calendula#71]
When I create a new "hourly interval", I can choose "Take X every Y hours", and am then asked for the first intake. I am not asked for the final intake. Is it possible to add such a field (perhaps make it optional), so I am not woken up at night by unnecessary reminders? Thank you.

**Comment by ontherunvaro** [comment]
Hello @symbolisch1234,

Routine schedules are what you're looking for! Hourly intervals are for when you need to take some medication exactly every X hours without exceptions.
If you want a more flexible scheme, for example taking a med at 8:00, 14:00 and 20:00, but not 2:00, you would need to define 3 routines (for 8:00, 14:00 and 20:00) and then setup a routine schedule with them.

**Comment by symbolisch1234** [comment]
Hi @ontherunvaro, thank you for your answer. Then please close this issue.

But then, for my use case (every 2hrs between 9:00 and 23:00) I need another enhancement: #74
