### ISSUE TITLE
Options arising from (+) button are not translated

### ISSUE THREAD

**Issue by symbolisch1234** [citiususc/calendula#72]
Even with my language in english, the menu items for adding a new schedule are still in spanish.

"Vinculada a rutinas" - Routine schedule
"Intervalo horario" - Hourly intervals
"Periodo + descanso" - Period + rest

Very strange, as these actually are translated in line 352 and following in
https://github.com/citiususc/calendula/blob/master/Calendula/src/main/res/values/strings.xml#L352

**Comment by ontherunvaro** [comment]
This is fixed in the development branch, it will be published soon!

**Comment by symbolisch1234** [comment]
this is resolved in v2.4.1
