### ISSUE TITLE
[LowPrio] Notifications could be more informative

### ISSUE THREAD

**Issue by symbolisch1234** [citiususc/calendula#73]
this is really low-priority, but it would be nice to add the actual medicine to take to the lockscreen notification. as you can see the "Remember to take your Meds" line is duplicated. Only by expanding the ntotification can I see which medicine I am supposed to take. And showing the icon associated with the medicine type would be just the icing on the cake.

![screenshot_calendula](https://cloud.githubusercontent.com/assets/16333258/24828671/667e72fa-1c62-11e7-9b68-03e8613635a4.png)
screenshot taken from LineageOS 14.1 (Nougat 7.1)

again, this is really low-priority, but i wanted to add this.

**Comment by ontherunvaro** [comment]
This has been improved in release 2.5.1, which has just been published on Github and Google Play, and should be on F-Droid soon.

Here's what the notification looks like now (also LineageOS 14.1):
![screenshot_20180208-105600](https://user-images.githubusercontent.com/8677743/35966692-dc04da62-0cbe-11e8-817e-dea155f064d3.png)

Thank you!
