### ISSUE TITLE
Notifications for different schedules conflict

### ISSUE THREAD

**Issue by symbolisch1234** [citiususc/calendula#75]
These two are closely related, so it may be a single bug. If not, feel free to split it into two issues.

Sometimes notifications for two different medicines conflict with each other. The current behaviour of Calendula makes it easy to forget taking one of the medicines.

##(1) Only one notification is shown##

**(1) Steps to reproduce**
1. Create "Med1" and "Med2"
2. Create hourly schedule for Med1 with 13:15 as the start date.
3. Create hourly schedule for Med2 with 13:15 as the start date.
4. Wait until 13:16.

**(1) Expected Behaviour**
Two notifications should appear on the lock screen, one for Med1, the other for Med2.

**(1) Actual Behaviour**
The notification for Med1 is shown. There is no notification for Med2.

##END (1)##

##(2) Both notifications are shown, but the second one is automatically dismissed.##

**(2) Steps to reproduce**
Create "Med1" and "Med2"
Create hourly schedule for Med1 with 13:15 as the start date.
Create routine schedule for Med2 with 13:15 as one of the dates.
Wait until 13:16, when two notifications appear.
Tap on the notification for Med1.
In Calendula, tap the checkmark indicating you have taken Med1.
Press either the arrow in the upper left, or the Android back button.

**(2) Expected Behaviour**
You should now be presented with the second Calendula screen for Med2, in order to tap the checkmark, indicating you have taken Med2. The notification for Med2 should still be there. 

**(2) Actual Behaviour**
You are immediately taken to the Calendula home screen. The notification for Med2 is gone.

**Comment by ontherunvaro** [comment]
Woops, closed the wrong issue!

**Comment by symbolisch1234** [comment]
both resolved in 2.4.1
