### ISSUE TITLE
readme.md screenshots are broken

### ISSUE THREAD

**Issue by symbolisch1234** [citiususc/calendula#76]
In https://github.com/citiususc/calendula/blob/master/README.md there is a section "How does it look?" with screenshots. The images seem to have been deleted.

**Comment by symbolisch1234** [comment]
Also on readme.md, so I don't have to open another issue:

Under the "Contributing" headline, there is a line:

`Notice that Calendula is licensed under the terms of the GPL v3 license, so by submitting content to the Calendula repository, you release your work to the public domain.`

But GPL is not the same as Public Domain. I suggest changing it to.

 `Notice that Calendula is licensed under the terms of the GPL v3 license, so by submitting content to the Calendula repository, you release your work under the terms of this license.`

**Comment by ontherunvaro** [comment]
Closed by https://github.com/citiususc/calendula/commit/0069a9528e263daa0f5ae730a28dff6761508104
