### ISSUE TITLE
Problems with timezone, I think.

### ISSUE THREAD

**Issue by aensidhe** [citiususc/calendula#77]
Look to screenshot in attachment. Time is 14:37 GMT+3, default routine "Dinner" is used. It set to 21:00. Looks like more than 5 hours till intake, but app shows "5 hours".
![2017-04-23 02 41 03](https://cloud.githubusercontent.com/assets/3948027/25313200/e79b5458-2832-11e7-90a7-3096932b6834.jpg)

**Comment by ontherunvaro** [comment]
Hello @aensidhe ,

Could you check if this is still happening in version  2.5.1 (just published? Thanks!

**Comment by ontherunvaro** [comment]
Hello,

I am closing this issue because it's stale and we can't reproduce it.
