### ISSUE TITLE
Alternative Download location

### ISSUE THREAD

**Issue by IzzySoft** [citiususc/calendula#82]
With the app being open source, would you mind having it brought to F-Droid – or at least attach an `.apk` file to its `releases/`?

**Comment by angelpinheiro** [comment]
Calendula is already on F-Droid, but we do not maintain it and for now we do not plan to do so. I think uploading the APK for each release is a good idea, we'll start doing that. Thanks!

**Comment by IzzySoft** [comment]
If it's already on F-Droid (great! Will check that ASAP), you could also add a "badge" next to the Playstore one (there is a similar "button image" for "Get it on F-Droid", which is used by multiple projects here at Github already) to make people aware of it. Goes "both ways" then, promoting F-Droid with your app and vice versa :stuck_out_tongue_winking_eye:

**Comment by ontherunvaro** [comment]
@IzzySoft I've attached the 2.4 APK to the corresponding release. Thanks for the suggestion!

**Comment by IzzySoft** [comment]
Thanks a lot! As it seems F-Droid hasn't updated the app since v2.3.3 back in 2015, I've decided to [include it with my repo](https://apt.izzysoft.de/fdroid/index/apk/es.usc.citius.servando.calendula) (taking the APK you've just attached). So if you keep that custom of attaching an `.apk` file to each new release, it should appear within my repo within 24h after that, usually.

Apart from which, it sits on the top place in my [list of medicine helpers](https://android.izzysoft.de/applists/category/named/health_medicine#group_1010) :+1:

**Comment by ontherunvaro** [comment]
@IzzySoft I've actually fixed the FDroid build earlier today, so it should be available there whenever they do a rebuild.

**Comment by IzzySoft** [comment]
That's great! No contradiction, though: At least currently, F-Droid builds and signs with *their* signature, while I take the `.apk` with *yours* (so people "on the switch" from Playstore to F-Droid could easily cross-update). However: If you wish that I remove your app from my repo, just let me know and I'll of course comply.

PS: Don't forget the F-Droid button on the `README.md`, next to the "Get it on Google Play" one :wink:

**Comment by IzzySoft** [comment]
@ontherunvaro F-Droid currently seems to have even the newer versions (they're on 2.4.1 which you haven't even tagged). So to avoid confusion, I will now unlist it from my repo (i.e. "archiving" the metadata). If need arises at any point, just let me know and I can easily restore it (as long as you provide the `.apk` that is).

Thanks again!
