### ISSUE TITLE
"Taken" button in notification

### ISSUE THREAD

**Issue by laurentlbm** [citiususc/calendula#84]
As a user, I would like to have a "Taken" button in the notification, so that I don't have to go in the app.

**Comment by ontherunvaro** [comment]
Hi @laurentlbm,
This is already implemented in the development branch. I will let you know once we release a version with these changes!

**Comment by Rudloff** [comment]
Any news on this?
This would be very useful to me because it would allow me to use the "Taken" action directly from my watch.

**Comment by ontherunvaro** [comment]
This is available on release 2.5.1, which has just been published on Github and Google Play, and should be available in F-Droid soon.

Thank you for the feedback!
