### ISSUE TITLE
Cannot change time of routines on Android 4.2.2

### ISSUE THREAD

**Issue by woutersj** [citiususc/calendula#86]
I have installed Calendula 2.4.1 (30) from the f-droid repository. On Android 4.2.2, I can't change the time connected to a routine. I only get a dialog to select a time, without a way to set it (see screenshot). On Android 7.1.2 I get a different, functioning, dialog.

![screenshot_2017-08-09-14-06-26](https://user-images.githubusercontent.com/4056484/29120804-41370128-7d0c-11e7-8612-94395ceaf7bc.png)

**Comment by ontherunvaro** [comment]
Hi @woutersj, can you let us know what device this is happening in? Screen size and density seem to be important to this behaviour, so that info will let us test it more accurately.

**Comment by woutersj** [comment]
Sure, this was on a Fairphone 1, with a 960×540 px resolution.

"Álvaro Brey" <notifications@github.com> schreef op 29 augustus 2017 11:38:13 GMT+01:00:
