### ISSUE TITLE
Untranslated text remains in 2.4.1

### ISSUE THREAD

**Issue by symbolisch1234** [citiususc/calendula#87]
I am using an Xperia M running Lineage 14.1 (Android 7.1.1), and am on Calendula 2.4.1 (F-Droid). My system language is _English_.

* On the home tab, it says "tomate tus medicinas ahora" (??you have taken your medicine already??).
* The titles of the other three tabs are "Routines de Usuario", "Medicines de Usuario", and "Schedules de Usuario".
* In the second tab it says "Sin  pautas asociadas" (including the double space).
* In the Menu, when i choose "Patients", i come to a page titled "Pacientes", and a user image subtitled "Usuario". When I create a new user, it gives me the option "Crear rutinas por defecto"

possibly related to issue #72 (which i then might have closed prematurely)

**Comment by ontherunvaro** [comment]
Hi @symbolisch1234,

The 2.4.1 version on F-Droid only has very minor fixes and some patches for F-Droid compatibility over the 2.4 version, so it's expected that most bugs from 2.4 remain present.

Translations are done in the development branch, we'll let you know once a new version is out!

**Comment by ontherunvaro** [comment]
Hello!

We just released version 2.5.1 on Github and Google Play, and it will soon be on F-Droid too. All these translations errors have been corrected. Thank you!
