### ISSUE TITLE
Upgrade resets all settings

### ISSUE THREAD

**Issue by proedie** [citiususc/calendula#88]
Hello,

After upgrading from 2.3.3 to 2.4.1 (both from F-Droid) all settings are reset to default, all routines, medicines, and schedules are gone.

Cheers,

Jan

**Comment by ontherunvaro** [comment]
Hi @proedie,

We are sorry for the inconvenience caused. This was an untested migration path, and we have identified the problem. 
Unfortunately we can't really allocate resources to fix this, as it affects only an old version of Calendula that isn't even available on the main F-Droid repository anymore.

Either way, thanks for the report, and we hope that the new version is working fine for you.
