### ISSUE TITLE
Target views for Home screen and few small issues

### ISSUE THREAD

**Issue by iamjaspreetsingh** [citiususc/calendula#89]
Tap target view could be used in the Home for target icons of routines, medicines and schedules respectively. There are few libraries available on github for that like Taptargetview etc.
Few small issues I faced 
1 .Trying to add the patient the contact icon is not fully visible. 
2. While we go to Patients from side navigation menu, there is an unwanted Settings option in action bar which neither works. 
3. The app is also not supporting landscape orientation in any case. May be it is done intentionally.

**Comment by ontherunvaro** [comment]
Hello,

On target view: Thanks for the suggestion, but we feel that the first-user slider tutorial we have now, and the detailed tutorial for routine types are enough to let users know how to use the app. We will nonetheless take a look at the target view model and figure out if it's worth implementing.

Your issues 1 and 2 have been resolved in release 2.5.1. 

The app does not support landscape orientation intentionally, as it's not designed for such use, and it would look just plain weird if we allowed landscaping. We may add landscape support in the future, but there are no plans for now.

Thank you for all your feedback!
