### ISSUE TITLE
Some calculation or display is wrong on remaining medicines

### ISSUE THREAD

**Issue by onekk** [citiususc/calendula#90]
In the medicine screen the duration of the stock is wrong with 103 pills taken 2 times a day "7 months and 2 days" is displayed, I think it have to be "7 weeks and 2 days".

Calendula version 2.5.1 (32)
running on Andorind 5.1.1 (Samsung Galaxy j3 2016)

Regards

Carlo D.

**Comment by ontherunvaro** [comment]
Hi and thanks for the report!

We had already noticed, and we fixed this just yesterday in 1c5e8bdfb9cab8ef0fb94bf855db83fc57e6eed2. It will be fixed in the next release!

**Comment by ontherunvaro** [comment]
This is fixed in version 2.5.2, released today. Thank you!
