### ISSUE TITLE
Translatable play store descriptions

### ISSUE THREAD

**Issue by exploide** [citiususc/calendula#91]
After translating this app to German, I'm glad to see the first release with 100% German translation coverage out now. :)

But I noticed the play store description is mostly in Spanish, yet. The strings do not seem to be part of this repository at the moment. It would be great to have them also translated in order to get more people adopt this app. Currently non-Spanish speakers see the app (if they find it at all) and have no clue why this is a good app and why they should use this one instead of the other closed source apps.

I'm not familiar with the process of publishing apps to the play store, but after searching for it, it seems there are several possibilities to achieve localized descriptions. One of the possibilities seems to be whatever this (unrelated) app is doing (probably using fastlane for this?! don't know): https://github.com/westnordost/StreetComplete/tree/master/metadata

**Comment by angelpinheiro** [comment]
Hello @exploide, I really like the idea, we'll take a look at fastlane! Meanwhile I think we could create a `metadata` folder on the repo to store the information  shown in Google Play, in order to make it easier to translate. Thank you very much!

**Comment by ontherunvaro** [comment]
Hi @exploide, I've just added a metadata folder like the one from your example. 
Feel free to PR a German translation if you want, and we'll manually add it to Play Store.

We may look at an automated solution in the future, but for now we will have to do with this.

P.S: I've also changed the default translation on Play Store to English, which is a bit more international than Spanish :)

**Comment by ontherunvaro** [comment]
The Play Store descriptions have been updated, so I'm closing this for now. If we opt for something like fastlane in the future we'll reopen.
