### ISSUE TITLE
Welcome screen in Spanish minor text fixes proposed

### ISSUE THREAD

**Issue by gentakojima** [citiususc/calendula#95]
Literally reads as "Taking your medication properly is not meant to be easy, but now at least it won't be so difficult!" ("Tomar correctamente tu medicación no tiene por qué ser fácil, pero ahora al menos no será tan difícil")

Proposed text: "Tomar correctamente tu medicación no es fácil, pero ahora al menos no será tan difícil"

**Comment by ontherunvaro** [comment]
Corrections applied in Poeditor, will be applied to the repo Soon™. Thank you!

**Comment by ontherunvaro** [comment]
Done on release 2.5.3. Cheers!
